### ISSUE TITLE
Investigate a cli tool for seeding database

### ISSUE THREAD

**Issue by KerimCETINBAS** [edunota/edunota-database#3]
We need a tool can automatically seed database for us

# Possible approaches;
- write own cli 
- find a cli meet for our requirements
- write a mini project that seeds database tables
- write a shell script seeds databse with pgcli
- dump sql files manually seed database on spin up database

## Write our own cli
sarikiz syndrome; i dont know if anyone bother to write a new cli program

## find a cli tool
i think its best practice for us if we want a quick start

## write a project that seed tables
considerable but worst option for my opinion

## shell script
its good point to increase linux or shell script skills

## dump sql files manually seed database on spin up database
quicker but not too fancy
https://github.com/caglarcercinli/docker-pg-with-data/blob/master/docker-compose.yml

**Comment by caglarcercinli** [comment]
maybe best is to do it by shell-scripting: every team member will docker-compose up own local db and down.
